http:
  routers:
    phoenix-router:
      rule: "Host(`phoenix.django-cast.com`)"

      entryPoints:
        - web
      middlewares:
        - redirect
        - csrf
      service: phoenix

    phoenix-secure-router:
      rule: "Host(`phoenix.django-cast.com`)"

      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: phoenix
      tls:
        certResolver: letsencrypt

  middlewares:
    redirect:
      redirectScheme:
        scheme: https
        permanent: true
    csrf:
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    phoenix:
      loadBalancer:
        servers:
          - url: http://::1:8002
